### ISSUE TITLE
Request Zoom out further

### ISSUE THREAD

**Issue by djassoRaph** [brandon-ray/foxhole-facility-planner#14]
Hello. 

I'm trying to build a facility and planning for Tier 2 and Tier 3 buildings. I've noticed that you've made a fixed zoom. Is there a  way to improve that edit that? 

Thank you in advance for reading this. 

Great tool! :D

**Comment by jimdcunningham** [comment]
Raised the cap on zooming out. 👍

Hopefully that helps haha

**Comment by djassoRaph** [comment]
Hello.

Thank you very much.
