### ISSUE TITLE
Petrol Power Plant Upgrade cost is wrong

### ISSUE THREAD

**Issue by MarnusStoop** [brandon-ray/foxhole-facility-planner#15]
The website says it costs 50 processed construction materials(tier 2 material) to upgrade a diesel power plant into a petrol power plant. This is incorrect, it costs 100 construction materials(the tier 1 material)

![image](https://user-images.githubusercontent.com/8688364/193424974-b2325823-9dcb-4d2f-9db4-dd2f354681cc.png)

**Comment by jimdcunningham** [comment]
Done, thanks! 💙
