### ISSUE TITLE
Everything seems to cost 2 GS per hour

### ISSUE THREAD

**Issue by Darxo** [brandon-ray/foxhole-facility-planner#17]
The ingame descriptions say that Foundations cost `2x more Garrison Supplies` while non of the other Facility related structures have that line.

And yet you calculate the same upkeep cost for both Foundations and non-Foundations.

I wish I could also tell you the correct cost but I have no Idea how what `2x more` means. It could be 100% increased cost or 200% increased cost depending on how you interpret it.

**Comment by jimdcunningham** [comment]
Hopefully fixed this with the last commit. 👍
