### ISSUE TITLE
Suggestion: Add Pipes

### ISSUE THREAD

**Issue by ianfights** [brandon-ray/foxhole-facility-planner#19]
Pipe planning is one of the more important ones that can be very costly if done wrong. It would be a great addition to see pipes in the planner.

**Comment by jimdcunningham** [comment]
I so wish this was an easy thing to do. Ray has some plans to do this and considering he worked with rails the most I expect it'd be something he'll get to... at some point haha.

I probably won't touch this, but if someone else wants to have a crack at this, more power to ya haha. 👀

Curves man, math is hard. 😂

**Comment by ianfights** [comment]
> I so wish this was an easy thing to do. Ray has some plans to do this and considering he worked with rails the most I expect it'd be something he'll get to... at some point haha.
> 
> I probably won't touch this, but if someone else wants to have a crack at this, more power to ya haha. 👀
> 
> Curves man, math is hard. 😂

Good thing with pipes there are no curves, the tricky part is the logic for deciding where you can connect to
