### ISSUE TITLE
Suggestion: Group selection via shift click, or drag selection.

### ISSUE THREAD

**Issue by Skjolbir** [brandon-ray/foxhole-facility-planner#21]
Currently, if you want to move 10-15 things as a group, its a little tedious.

**Comment by jimdcunningham** [comment]
![image](https://user-images.githubusercontent.com/1763314/195166008-f097aa56-c329-4af4-9ea6-ddcdf631a6f7.png)

Currently have selection done. Attempting to add as many things in like locking, deleting, etc. for multiple buildings. It's been a wild ride these last couple of days haha. I had to rewrite a lot of code, but it's coming together pretty nicely.

#22 will be possible once I do all of this though, which is neat.
